-- Sử dụng CSDL đã tạo
USE QLPKNHAKHOA
GO
--
-- Delete data from the table 'dbo.ACCOUNT'
--
DELETE ACCOUNT
GO
--
-- Inserting data into table into ACCOUNT
--
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin1', '00A848', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin2', 'KWUQ7', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin3', '4', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin4', 'T3NO40JEX', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin5', '3L', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin6', 'Q8S', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin7', 'I', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin8', '15W45', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin9', '75I', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin10', '527T', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin11', 'R7', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin12', 'D8', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin13', '0', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin14', 'X', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin15', 'E9', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin16', 'DL2Q507C026274', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin17', 'Y', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin18', '7E8W7RH', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin19', 'CC5M970G', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Admin20', '3PJQO10XA', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi1', '00A848', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi2', 'KWUQ7', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi3', '4', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi4', 'T3NO40JEX', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi5', '3L', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi6', 'Q8S', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi7', 'I', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi8', '15W45', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi9', '75I', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi10', '527T', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi11', 'R7', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi12', 'D8', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi13', '0', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi14', 'X', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi15', 'E9', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi16', 'DL2Q507C026274', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi17', 'Y', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi18', '7E8W7RH', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi19', 'CC5M970G', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhasi20', '3PJQO10XA', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien1', '00A848', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien2', 'KWUQ7', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien3', '4', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien4', 'T3NO40JEX', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien5', '3L', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien6', 'Q8S', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien7', 'I', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien8', '15W45', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien9', '75I', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien10', '527T', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien11', 'R7', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien12', 'D8', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien13', '0', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien14', 'X', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien15', 'E9', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien16', 'DL2Q507C026274', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien17', 'Y', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien18', '7E8W7RH', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien19', 'CC5M970G', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Nhanvien20', '3PJQO10XA', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Letha241', '00A848', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Mollie1975', 'KWUQ7', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Quintin5', '4', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Kathern49', 'T3NO40JEX', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Felisa221', '3L', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Shenita2027', 'Q8S', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Arnita2004', 'I', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Woodrow2009', '15W45', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Chantel318', '75I', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Aisha2010', '527T', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Christopher1976', 'R7', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Stephan1976', 'D8', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Brinson972', '0', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Carpenter1994', 'X', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Doyle2', 'E9', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Johnston1952', 'DL2Q507C026274', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Booker6', 'Y', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Carvalho72', '7E8W7RH', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Aguilera1993', 'CC5M970G', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Paris2022', '3PJQO10XA', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Jerrod1982', '4X', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Suarez82', '306P', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Abreu232', '44GU1J34', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Shank212', 'HN4', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Elise28', 'N3USVDC', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Alcala1977', 'UE7230Q', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Abernathy6', 'K', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Lindsey295', 'C', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Hubert2025', 'ZD65Y4N545KJ2I', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Paris24', '1A', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Muncy1', '26', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Jestine2015', '9XWQ', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Alexander3', '375', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Seymour1989', 'M4U0E', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Lorretta2028', '85J6W', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Andre58', '5W4C', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Carlson9', 'L4223', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Jefferies7', 'I7H', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Verona3', 'DXG', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Lanette688', '4MZ3F49', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Crystle2000', 'I', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Weston1954', 'I', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Abdul134', 'S', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Brigida1989', 'Y', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Christian1985', '9', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Alberto1984', 'NB4RU8V', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Ernesto599', 'XGE9409', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Rivka533', 'ZWCF8', 'Yes')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Opal1955', 'X4544S', 'No')
INSERT into ACCOUNT(Username, Pass_word, isActive) VALUES ('Cornell6', 'P0V27', 'No')
GO