-- Sử dụng CSDL đã tạo
USE QLPKNHAKHOA
GO
--
-- Delete data from the table 'dbo.CONTRAINDICATION'
--
DELETE CONTRAINDICATION
GO
--
-- Inserting data into table into CONTRAINDICATION
--
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (75, 32)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (79, 6321)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (86, 138)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (4, 620)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (1, 8538)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (5, 177)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (8, 1)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (71, 8)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (12, 1969)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (5, 100)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (12, 39)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (33, 3)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (57, 133)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (13, 153)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (21, 154)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (287, 66)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (7, 95)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (11, 15)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (3, 6)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (17, 62)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (13, 16)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (14, 15)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (22, 12)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (53, 18)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (15, 86)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (1, 153)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (12, 15)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (25, 197)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (53, 126)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (12, 19)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (236, 117)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (19, 348)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (751, 1232)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (1570, 80)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (24, 11)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (30, 633)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (18, 887)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (27, 17)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (65, 285)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (13, 889)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (135, 51)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (237, 174)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (837, 15)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (11, 176)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (19, 624)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (52, 63)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (6, 18)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (5, 153)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (2, 10)
INSERT into CONTRAINDICATION(ID_Customer, ID_Medicine) VALUES (1, 12)
GO