-- Sử dụng CSDL đã tạo
USE QLPKNHAKHOA
GO
--
-- Delete data from the table 'dbo.APPOINTMENT'
--
DELETE DENTIST
GO
--
-- Inserting data into table into DENTIST
--
INSERT into DENTIST(ID_Dentist) VALUES (1)
INSERT into DENTIST(ID_Dentist) VALUES (2)
INSERT into DENTIST(ID_Dentist) VALUES (3)
INSERT into DENTIST(ID_Dentist) VALUES (4)
INSERT into DENTIST(ID_Dentist) VALUES (5)
INSERT into DENTIST(ID_Dentist) VALUES (6)
INSERT into DENTIST(ID_Dentist) VALUES (7)
INSERT into DENTIST(ID_Dentist) VALUES (8)
INSERT into DENTIST(ID_Dentist) VALUES (9)
INSERT into DENTIST(ID_Dentist) VALUES (10)
INSERT into DENTIST(ID_Dentist) VALUES (11)
INSERT into DENTIST(ID_Dentist) VALUES (12)
INSERT into DENTIST(ID_Dentist) VALUES (13)
INSERT into DENTIST(ID_Dentist) VALUES (14)
INSERT into DENTIST(ID_Dentist) VALUES (15)
INSERT into DENTIST(ID_Dentist) VALUES (16)
INSERT into DENTIST(ID_Dentist) VALUES (17)
INSERT into DENTIST(ID_Dentist) VALUES (18)
INSERT into DENTIST(ID_Dentist) VALUES (19)
INSERT into DENTIST(ID_Dentist) VALUES (20)
GO