USE QLPKNHAKHOA
--Create index on column DOB of table CUSTOMER 
CREATE NONCLUSTERED INDEX index_CUSTOMER_DOB
ON CUSTOMER (DOB)

GO

--Create index on column ID_Customer of table SELECT_TREATMENT 
CREATE NONCLUSTERED INDEX index_SELECTTREATMENT_IDCustomer
ON SELECT_TREATMENT (ID_Customer)

GO